version: '3.8'

services: 
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network
  
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://username:password@db:5432/tododb
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
